apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: init-container-pvc
  namespace: amrit-test
  annotations:
    volume.beta.kubernetes.io/storage-class: "my-gp2"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
