---
- name: Deploy a simple static website
  hosts: localhost
  vars:
    packages:
      - git
      - vim
      - ruby
      - httpd
    html_dir: /var/www/html
    app_dir: /var/www/html/app
    repo: https://github.com/ladieslearningcode/llc-html-css-multi-page-site.git
  tasks:
    - 
        name: Httpd Group
        group: name=httpd
    - 
        name: Add Httpd User
        user:
          name: httpd
          shell: /bin/bash
          home: /home/httpd
          group: httpd
    - 
        name: Install httpd
        package: name="{{ item }}" state=present
        with_items: "{{ packages }}"
    - 
        name: Start and Enable Httpd service
        service:
          name: httpd
          enabled: yes
          state: started
    - 
        name: Ensure html dir exists
        file: path="{{ html_dir }}" state=directory owner=httpd group=httpd
    
    - 
        name: Create App Dir
        file: path="{{ app_dir }}" state=directory owner=httpd group=httpd
    - 
        name: Deploy sample static website
        git:
           clone: yes
           dest: "{{ app_dir }}"
           repo: "{{ repo }}"
