apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: artifactory-deployment
spec:
  selector:
    matchLabels:
      app: artifactory
  replicas: 1
  template:
    metadata:
      labels:
        app: artifactory
    spec:
      containers:
      - name: artifactory
        image: agill17/jfrog_artifactory
        ports:
        - containerPort: 8081
