language: ruby
rvm:
  - 2.2
# command to install dependencies
install:
  - gem install rubocop -v "0.44.1"
  - gem install foodcritic
# command to run tests
script:
  - cd ..
  - foodcritic tomcat_aws_provisioning
  - rubocop tomcat_aws_provisioning/recipes/vpc.rb
  - rubocop tomcat_aws_provisioning/recipes/tomcat_elb.rb