apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: app-deployment
  namespace: py-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      run: app-deployment
  template:
    metadata:
      labels:
        run: app-deployment
    spec:
      containers:
      - name: app-container
        image: agill17/flask_mysql_app:latest
        ports:
        - name: app-port
          containerPort: 3000
        livenessProbe:
          successThreshold: 1
          failureThreshold: 1
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 10
          timeoutSeconds: 10
        env:
          - name: MYSQL_USERNAME
            valueFrom: 
              configMapKeyRef:
                name: db-conf
                key: username
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-creds
                key: password
          - name: MYSQL_INSTANCE_NAME
            valueFrom:
              configMapKeyRef:
                name: db-conf
                key: db-name
          - name: MYSQL_SVC_HOST
            value: "db-svc"
          - name: MYSQL_PORT_3306_TCP_PORT
            value: "3306"
