apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: py-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      db: mysql
  template:
    metadata:
      labels:
        db: mysql
    spec:
      containers:
      - name: mysql-container
        image: mysql:5.7
        args:
          - "--ignore-db-dir=lost+found"
        volumeMounts:
        - name: db-ebs
          mountPath: /var/lib/mysql
        ports:
        - name: mysql-port
          containerPort: 3306
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-creds
                key: password
          - name: MYSQL_USER
            valueFrom:
              configMapKeyRef:
                name: db-conf
                key: username
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-creds
                key: password
          - name: MYSQL_DATABASE
            valueFrom:
              configMapKeyRef:
                name: db-conf
                key: db-name
      volumes:
      - name: db-ebs
        persistentVolumeClaim:
          claimName: py-mysql-pvc
