apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      db: mysql
  template:
    metadata:
      labels:
        db: mysql
    spec:
      containers:
      - name: mysql-container
        image: mysql:5.7
        ports:
        - name: mysql-port
          containerPort: 3306
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-creds
                key: password
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: db-creds
                key: username
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-creds
                key: password
          - name: MYSQL_DATABASE
            value: "db_name"
      nodeSelector:
        provider: aws
        env: dev
