apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-rules
  namespace: py-mysql
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: mypyapp.amritgill.tk
      http:
        paths:
          - path: /
            backend:
              serviceName: app-svc
              servicePort: 80
