apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: py-mysql-pvc
  namespace: py-mysql
  annotations:
    volume.beta.kubernetes.io/storage-class: "py-mysql-storage-class"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
