
enabled: true
image: agill17/kafka-statefulset:latest
replicas: 3
pullPolicy: Always
kfkHeadlessSvcName: kfk-headless
dataDir: /var/logs/kafka
persistence:
  enabled: true
  pvcSize: 10Gi
  accessModes: 
  - ReadWriteOnce
  storageClassName: gp2

svPort: 9092
targetPort: 9092
topics:
- name: test
  partitions: 1
  replicationFactor: 1
- name: test.test
  partitions: 1
  replicationFactor: 1
