apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.11
        volumeMounts:
        - name: nginx-conf
          mountPath: /etc/nginx/conf.d
        ports:
        - name: nginx-port
          containerPort: 80
      - name: k8s-demo
        image: wardviaene/k8s-demo
        ports:
        - containerPort: 3000
      volumes:
        - name: nginx-conf
          configMap:
            name: reverse-proxy
            items:
            - key: reverseproxy.conf
              path: reverseproxy.conf
        
