apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: app-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-1
  template:
    metadata:
      labels:
        app: app-1
    spec:
      containers:
      - name: app-1
        image: wardviaene/k8s-demo
        ports:
        - name: app-1-port
          containerPort: 3000

