apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: app-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-2
  template:
    metadata:
      labels:
        app: app-2
    spec:
      containers:
      - name: app-2
        image: wardviaene/k8s-demo:2
        ports:
        - name: app-2-port
          containerPort: 3000

