apiVersion: v1
kind: Service
metadata:
  name: kafka-headless
  namespace: kafka-zookeeper
spec:
  clusterIP: None
  ports:
    - name: main
      port: 9092
      targetPort: 9092
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: kafka-zookeeper
spec:
  ports:
    - name: main
      port: 9092
      targetPort: 9092