apiVersion: apps/v1
kind: StatefulSet
metadata:
    name: kafka
    namespace: kafka-zookeeper
spec:
  serviceName: kafka-headless
  replicas: 3
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: agill17/kafka-statefulset
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: ZOOKEEPER
          value: zookeeper:2181
        volumeMounts:
        - name: data
          mountPath: /data
        ports:
          - name: main
            containerPort: 9092
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
      storageClassName: gp2
  