---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sleep-wakeup
  namespace: {{ .Release.Namespace }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: {{ .Release.Namespace }}
  name: sleep-wakeup-role
rules:
- apiGroups: ["apps","extensions"] # "" indicates the core API group
  resources: ["deployments", "deployments/scale", "statefulsets", "statefulsets/scale"]
  verbs: ["get", "list", "update"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sleep-wakeup-rolebinding
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: sleep-wakeup
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: sleep-wakeup-role
  apiGroup: rbac.authorization.k8s.io