apiVersion: v1
kind: Namespace
metadata:
  name: test-ns

---
## Role defines access level permissions
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: user-role
  namespace: test-ns
rules:
- apiGroups: [""]
  resources: ["pods", "secrets", "configmaps"]
  verbs: ["get", "watch", "list", "create", "update", "delete"]
- apiGroups: ["apps/v1"]
  resources: ["deployments", "statefulsets"]
  verbs: ["get", "watch", "list"]
---
## RoleBinding assigns users/groups/serviceAccounts to roles
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: user-role-binding
  namespace: test-ns
subjects:
- kind: User
  name: test-user
  apiGroup: rbac.authorization.k8s.io
roleRef:
- kind: Role
  name: user-role
  apiGroup: rbac.authorization.k8s.io
