apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: sample-deployment
  namespace: myns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        volumeMounts:
        - name: myvol
          mountPath: "/tmp"
        ports:
        - name: nginx
          containerPort: 80
      volumes:
      - name: myvol
        persistentVolumeClaim:
          claimName: pvc