kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc
  namespace: myns
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  ### optional if default class is okay, but incase you need specify pvc to use a diff storageClass
  storageClassName: "ebs"