---
driver:
  name: vagrant
  network:
  - ['forwarded_port', {guest: 80, host: 7676}]

provisioner:
  name: chef_zero

  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04
  - name: centos-7

suites:
  - name: default
    run_list:
      - recipe[Gitlab::default]
      - recipe[Gitlab::Gitlab]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
    excludes:
      ubuntu-16.04
