apiVersion: v1
kind: Service
metadata:
  name: zookeeper-for-clients
  namespace: zookeeper
spec:
  selector:
    app: zookeeper
  ports:
    - name: main
      port: 2181
      targetPort: 2181

--- 
apiVersion: v1
kind: Service
metadata:
  name: zk-internal
  namespace: zookeeper
spec:
  clusterIP: None
  selector:
    app: zookeeper
  ports:
    - name: server
      port: 2888
      targetPort: 2888
    - name: leader-election
      port: 3888
      targetPort: 3888