kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: zookeeper
  namespace: zookeeper
spec:
  serviceName: zk-internal
  replicas: 3
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
      - name: zookeeper
        image: "agill17/zk-statefulset"
        env:
          - name: ZOOKEEPER_REPLICAS
            value: "3"
        ports:
        - name: client
          containerPort: 2181
        - name: leader-election
          containerPort: 3888
        - name: server
          containerPort: 2888
        volumeMounts:
          - name: data
            mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: 
        - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
      storageClassName: gp2
