{{- $kafkaName := include "kafka.name" . -}}
{{- $root := . -}}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ $kafkaName }}-create-topics-config
  namespace: {{ .Release.Namespace }}
data:
  create.sh: |
    #!/usr/bin/env bash
    set -x
    {{- range $i, $topic := .Values.topics }}
    /opt/kafka/bin/kafka-topics.sh --zookeeper zookeeper:2181 --create --if-not-exists --force --topic {{ $topic.name }} --partitions {{ $topic.partitions }} --replication-factor {{ $topic.replicationFactor}}
    {{- end }}