{{- $kafkaName := include "kafka.name" . -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $kafkaName }}-headless
  namespace: {{ .Release.Namespace }}
spec:
  clusterIP: None
  ports:
    - name: main
      port: {{.Values.svcPort }}
      targetPort: {{.Values.targetPort }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $kafkaName }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: main
      port: {{.Values.svcPort }}
      targetPort: {{.Values.targetPort }}