---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: myClusterDomain.com
  name: web-b
spec:
  image: kope.io/k8s-1.10-debian-jessie-amd64-hvm-ebs-2018-08-17
  machineType: t2.micro
  maxSize: 5
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: web-b
    nodeSelectorKeyNameHere: web
  role: Node
  subnets:
  - web-b