---
# tasks file for deploy_app


- name: Ensure html dir exists
  file: path="{{ html_dir }}" state=directory owner=httpd group=httpd

- name: Create App Dir
  file: path="{{ app_dir }}" state=directory owner=httpd group=httpd

- name: Deploy sample static website
  git:
    clone: yes
    dest: "{{ app_dir }}"
    repo: "{{ repo }}"

