apiVersion: v1
kind: Service
metadata:
  name: tomcat-elb-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: tomcat-app-port
    protocol: TCP
  selector:
    app: tomcat

---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: tomcat-app-deployment
spec:
  selector:
    matchLabels:
      app: tomcat
  replicas: 4
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
      - name: tomcat
        image: agill17/tomcat:latest
        ports:
        - name: tomcat-app-port
          containerPort: 8080
      nodeSelector:
        env: dev
        provider: aws
